apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-springboot-app-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eks-springboot-app-deploy
  template:
    metadata:
      labels:
        app: eks-springboot-app-deploy
    spec:
      containers:
      - name: my-custom-springboot-app
        image: accountid.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eks-springboot-app-service
    k8s-app: springboot-app
  name: springboot-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: eks-springboot-app-service
